env:
  global:
    - CONNECT_SERVER=https://apps.koverholt.com
    - APP_GUID=051e67e3-06fe-41c8-8ef6-a408a331a4c5
    - secure: tW/gzS20QyA+aIO4bm65OMfNSUqz7qf3TXK4I04gidSluuNjkhLjYUK56wbxoTcqrYPVJUb/YCOmT+oZi8NbclHMFRREoHf0jFv0RwPoOpyYbRILnKdJ5MrusfEQZ0IJURv2sSlzRzkzet7+S4oWx/9c8zW9rQkjCQn2U9TXd1t/2xgoFq1viWBUFclHUUaxMwfk3/jw/Vmm7hC83PNxDQfRFXFusiahdjMM379dk+jLkcgjLbvINzM8iZg4Mq07sjthiXuoibX9O3uhuvDUw1dTiIEwW5m1UOn8dgapCSV/FdAo5S3zqvtJlHahVVQBMQDF6gQJ20EEHBT85Ub+fVhzye3qpPuvlNmFU3WcYFD1CKWH/YcsSGdd1AMt8fPD7K3Y/XnePonfcRiZbPF76hMx5s4QOHXnKoNL4Mo50aMLDY+ePVWGrkbPj6agjLrR3tcuLm5cdSdnnwDKFUe/B8J21MN8U6p0N/+riAfkoAJM/hAYAvXNDrNw0C2CE4uUjzlQoELhntq0d3vd9IuZbRwIJ9avu63d7r9Tmnf4KQw2wHK7pE/kk8x3Zn6akMeyDxhd5mVNT2Lp8+RSnEAnm9xaz8tS4dCUXN1VtZ6cqQNZ4/hheeqw72018+K121xWabtLASzNVc7ZXiEjXIEn+EBzJkweOCyEL5+CeRu8ccA=

script: bash upload_and_deploy.sh ${APP_GUID} ./shiny-app/
